# Generated by Django 3.2.16 on 2022-11-21 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7)),
                ('type_component', models.CharField(choices=[('No definido', 'No definido'), ('Sillin', 'Sillin'), ('Ruedas', 'Ruedas'), ('Manillar', 'Manillar'), ('Cámara rueda', 'Cámara rueda'), ('Cuadro de la bici', 'Cuadro de la bici')], default='No definido', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ComponentBike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionPedidos.bike')),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionPedidos.component')),
            ],
        ),
    ]
