# Generated by Django 3.2.16 on 2022-11-21 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gestionPedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentsInCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionPedidos.cart')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionPedidos.component')),
            ],
        ),
        migrations.CreateModel(
            name='BikesInCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionPedidos.bike')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionPedidos.cart')),
            ],
        ),
    ]
