# Generated by Django 3.2.16 on 2022-11-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0002_bikesincart_cart_componentsincart'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
