# Generated by Django 3.2.16 on 2022-12-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='image',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
