# Generated by Django 3.2.16 on 2022-11-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0003_bike_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='price',
        ),
        migrations.AddField(
            model_name='bike',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
