# Generated by Django 3.2.16 on 2022-12-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0003_bike_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='type_component',
            field=models.CharField(choices=[('No definido', 'No definido'), ('SL', 'SL'), ('RD', 'RD'), ('MN', 'MN'), ('CR', 'CR'), ('CB', 'CB')], default='No definido', max_length=255),
        ),
    ]
