# Generated by Django 3.2.16 on 2022-11-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0004_auto_20221121_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='component',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
