# Generated by Django 3.2.16 on 2022-11-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0004_auto_20221121_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='name',
            field=models.CharField(default='Carro', max_length=30),
        ),
    ]
