# Generated by Django 3.2.16 on 2022-11-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0005_cart_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='name',
            field=models.CharField(auto_created=True, max_length=30),
        ),
    ]
