# Generated by Django 3.2.16 on 2022-11-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0009_alter_component_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='component',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
