# Generated by Django 3.2.16 on 2022-12-09 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0009_alter_component_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='image',
        ),
    ]
