# Generated by Django 3.2.16 on 2022-12-09 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0007_auto_20221130_1753'),
        ('gestionPedidos', '0009_alter_component_image'),
    ]

    operations = [
    ]
