# Generated by Django 3.2.16 on 2022-12-09 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0010_merge_20221209_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='image',
        ),
    ]
