# Generated by Django 3.2.16 on 2022-11-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0011_auto_20221129_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='image',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='image',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
