# Generated by Django 3.2.16 on 2022-12-09 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0011_remove_bike_image'),
        ('gestionPedidos', '0012_auto_20221129_1830'),
    ]

    operations = [
    ]
