# Generated by Django 3.2.16 on 2022-12-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0013_merge_0011_remove_bike_image_0012_auto_20221129_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='image',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='image',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
