# Generated by Django 3.2.16 on 2022-12-09 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0014_auto_20221209_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='image',
        ),
    ]
